name: CCTVCraft 5 - Bug Report
description: Report an issue with the modification!
title: "[Bug] <title>"
labels: [New, Bug]
body:
- type: textarea
  attributes:
    label: Issue Description
    description: Describe the issue what happens and what steps we can take to trigger the issue.
    placeholder: Your issue description.
  validations:
    required: true
- type: dropdown
  attributes:
    label: Versions
    options:
      - "CCTVCraft 5 (1.1.0) / NeoForge (1.21.1)"
      - "CCTVCraft 5 (1.0.0) / Forge (1.20.1)"
  validations:
    required: true
- type: textarea
  attributes:
    label: Crash Report
    description: Provide a crash file from your game or server.
    placeholder: Only required if there was a crash.
  validations:
    required: false
