blank_issues_enabled: false
contact_links:
  - name: CCTVCraft 5 - Ideas & Feature Requests
    url: https://github.com/northwesttrees-gaming/cctvcraft5/discussions/categories/suggestions
    about: Share ideas and feature requests here.
  - name: CCTVCraft 5 - Wiki
    url: https://github.com/northwesttrees-gaming/cctvcraft5/wiki
    about: Learn how the mod works on the official wiki.
