blank_issues_enabled: true
contact_links:
  - name: CCTVCraft 5 - Ideas & Feature Requests
    url: https://github.com/northwesttrees-gaming/cctvcraft5/discussions/categories/suggestions
    about: Official place to share feature requests.
  - name: CCTVCraft 5 - Wiki
    url: https://github.com/northwesttrees-gaming/cctvcraft5/wiki
    about: Official wiki for the modification.
